### ⛔️ THIS FILE IS FOR VS-CODE text editor only!!!
### Install a VS-CODE plugin called REST Client
### Then you will be able to make API request from this file


### Test Server
GET http://localhost:4000 HTTP/1.1



### Get goals
GET http://localhost:4000/api/goals HTTP/1.1



### Add goal
POST http://localhost:4000/api/goals HTTP/1.1
content-type: application/json

{
    "text": "My 4 goal"
}



### Update goal
PUT http://localhost:4000/api/goals/626ac5d2ebc75ae50563102a
content-type: application/json

{
    "text": "My 2 goal"
}


### Delete goal
DELETE http://localhost:4000/api/goals/626accdeca7a17b14d3d2dff



### Register user
POST http://localhost:4000/api/users HTTP/1.1
content-type: application/json

{
    "name": "string", "email": "string", "password": "string"
}



### Login user
POST http://localhost:4000/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "string", "password": "string"
}