### variables
@localhost=http://localhost:8080


### test default server
GET {{localhost}}


### register route
POST {{localhost}}/api/register
content-type: application/json

{
    "username": "hardy",
    "email": "hardy@example.com",
    "password": "123456",
    "profile": ""
}


### login route
POST {{localhost}}/api/login
content-type: application/json

{
    "username": "hardy",
    "password": "123456"
}